### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by ghost** [wequant-org/triangle-arbitrage#1]
2017-07-29 03:09:38,224 - triangle_main.py[line:143] - ERROR: Traceback (most recent call last):
  File "triangle_main.py", line 83, in strategy
    huobi_market.market_detail(self.base_cur, self.quote_cur)
  File "/root/triangle-arbitrage/marketHelper.py", line 41, in market_detail
    return exchangeConnection.pro.proService.ProServiceAPIKey().get_depth("ltcbtc").get("tick")
  File "/root/triangle-arbitrage/exchangeConnection/pro/proService.py", line 219, in get_depth
    ret = key_api.get_depth(symbol, type=type)
  File "/root/triangle-arbitrage/exchangeConnection/pro/key_api.py", line 139, in get_depth
    return http_get_request(url, params)
  File "/root/triangle-arbitrage/exchangeConnection/pro/key_api.py", line 34, in http_get_request
    raise Exception("httpGet failed, detail is:%s" % response.text)
Exception: httpGet failed, detail is:<!DOCTYPE html>
<html>

**Comment by hyfwin** [comment]
it's about user-agent of header,I have fixed it

**Comment by beaquant** [comment]
great!
